package com.livingtechusa.reflexion.ui.theme.selectableColorSchemes

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val md_theme_5_light_primary = Color(0xFF825500)
val md_theme_5_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_5_light_primaryContainer = Color(0xFFFFDDAE)
val md_theme_5_light_onPrimaryContainer = Color(0xFF2A1800)
val md_theme_5_light_secondary = Color(0xFF6F5B40)
val md_theme_5_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_5_light_secondaryContainer = Color(0xFFFADEBC)
val md_theme_5_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_5_light_tertiary = Color(0xFF516440)
val md_theme_5_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_5_light_tertiaryContainer = Color(0xFFD3EABC)
val md_theme_5_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_5_light_error = Color(0xFFBA1B1B)
val md_theme_5_light_errorContainer = Color(0xFFFFDAD4)
val md_theme_5_light_onError = Color(0xFFFFFFFF)
val md_theme_5_light_onErrorContainer = Color(0xFF410001)
val md_theme_5_light_background = Color(0xFFFCFCFC)
val md_theme_5_light_onBackground = Color(0xFF1F1B16)
val md_theme_5_light_surface = Color(0xFFFCFCFC)
val md_theme_5_light_onSurface = Color(0xFF1F1B16)
val md_theme_5_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_5_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_5_light_outline = Color(0xFF817567)
val md_theme_5_light_inverseOnSurface = Color(0xFFF9EFE6)
val md_theme_5_light_inverseSurface = Color(0xFF34302A)
val md_theme_5_light_inversePrimary = Color(0xFFFFB945)
val md_theme_5_light_surfaceTint = Color(0xFF006874)
val md_theme_5_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_5_light_scrim = Color(0xFF000000)

val md_theme_5_dark_primary = Color(0xFFFFB945)
val md_theme_5_dark_onPrimary = Color(0xFF452B00)
val md_theme_5_dark_primaryContainer = Color(0xFF624000)
val md_theme_5_dark_onPrimaryContainer = Color(0xFFFFDDAE)
val md_theme_5_dark_secondary = Color(0xFFDDC3A2)
val md_theme_5_dark_onSecondary = Color(0xFF3E2E16)
val md_theme_5_dark_secondaryContainer = Color(0xFF56442B)
val md_theme_5_dark_onSecondaryContainer = Color(0xFFFADEBC)
val md_theme_5_dark_tertiary = Color(0xFFB8CEA2)
val md_theme_5_dark_onTertiary = Color(0xFF243516)
val md_theme_5_dark_tertiaryContainer = Color(0xFF3A4C2B)
val md_theme_5_dark_onTertiaryContainer = Color(0xFFD3EABC)
val md_theme_5_dark_error = Color(0xFFFFB4A9)
val md_theme_5_dark_errorContainer = Color(0xFF930006)
val md_theme_5_dark_onError = Color(0xFF680003)
val md_theme_5_dark_onErrorContainer = Color(0xFFFFDAD4)
val md_theme_5_dark_background = Color(0xFF1F1B16)
val md_theme_5_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_5_dark_surface = Color(0xFF1F1B16)
val md_theme_5_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_5_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_5_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_5_dark_outline = Color(0xFF9C8F80)
val md_theme_5_dark_inverseOnSurface = Color(0xFF32281A)
val md_theme_5_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_5_dark_inversePrimary = Color(0xFF624000)
val md_theme_5_dark_surfaceTint = Color(0xFF4FD8EB)
val md_theme_5_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_5_dark_scrim = Color(0xFF000000)